Traodoisub/TraoiDoiSubb/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TraoiDoiSubb.DataEFs.DataAccesLayers.Interfaces;
using TraoiDoiSubb.Models;

namespace TraoiDoiSubb.Controllers
{
  //  [Route("account")]
    public class AccountsController : Controller
    {
        private readonly ITaikhoanDataAccessLayer _taikhoanDataAccessLayer;
        private readonly INotyfService _notyf;
        public AccountsController(ITaikhoanDataAccessLayer taikhoanDataAccessLayer, INotyfService notyf)
        {
            _taikhoanDataAccessLayer = taikhoanDataAccessLayer;
            _notyf = notyf;
        }
        //[Route("")]
        //[Route("index")]
        //[Route("~/")]
        public IActionResult Index()
        {
            return View();
        }


       
        [HttpPost]
        public IActionResult Login(TaiKhoan taiKhoan)
        {
            if (taiKhoan.UserName != null && taiKhoan.Password != null&& _taikhoanDataAccessLayer.CheckExitAccount(taiKhoan))
            {   
                    var taikhoanData = _taikhoanDataAccessLayer.GetInforTaiKhoan(taiKhoan.UserName);
                    HttpContext.Session.SetString("fullname", taikhoanData.FullName);
                    HttpContext.Session.SetString("username", taikhoanData.UserName);
                    _notyf.Success("Đăng nhập thành công");
                    return RedirectToAction("Index", "Home");   
            }
            else
            {
            
                return RedirectToAction("Index");
              
            }
        }

        [Route("logout")]
        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("username");
            return RedirectToAction("Index");
        }
    }
}

Traodoisub/TraoiDoiSubb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Enlink - Admin Dashboard Template</title>


    <!-- Favicon -->
    <link rel="shortcut icon" href="~/assets/images/logo/favicon.png">

    <!-- page css -->
    <link href="~/assets/vendors/datatables/dataTables.bootstrap.min.css" rel="stylesheet">

    <!-- Core css -->
    <link href="~/assets/css/app.min.css" rel="stylesheet">

</head>

<body>
    <div class="app">
        <div class="layout">
            <!-- Header START -->
            <div class="header">
                <div class="logo logo-dark">
                    <a asp-action="Index" asp-controller="Home">
                        <img src="~/assets/images/logo/logo.png" alt="Logo">
                        <img class="logo-fold" src="~/assets/images/logo/logo-fold.png" alt="Logo">
                    </a>
                </div>
                <div class="logo logo-white">
                    <a asp-action="Index" asp-controller="Home">
                        <img src="~/assets/images/logo/logo-white.png" alt="Logo">
                        <img class="logo-fold" src="~/assets/images/logo/logo-fold-white.png" alt="Logo">
                    </a>
                </div>
                <div class="nav-wrap">
                    <ul class="nav-left">
                        <li class="desktop-toggle">
                            <a href="javascript:void(0);">
                                <i class="anticon"></i>
                            </a>
                        </li>
                        <li class="mobile-toggle">
                            <a href="javascript:void(0);">
                                <i class="anticon"></i>
                            </a>
                        </li>
                        <li>
                            <a href="javascript:void(0);" data-toggle="modal" data-target="#search-drawer">
                                <i class="anticon anticon-search"></i>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav-right">
                        <li class="dropdown dropdown-animated scale-left">
                            <a href="javascript:void(0);" data-toggle="dropdown">
                                <i class="anticon anticon-bell notification-badge"></i>
                            </a>
                            <div class="dropdown-menu pop-notification">
                                <div class="p-v-15 p-h-25 border-bottom d-flex justify-content-between align-items-center">
                                    <p class="text-dark font-weight-semibold m-b-0">
                                        <i class="anticon anticon-bell"></i>
                                        <span class="m-l-10">Notification</span>
                                    </p>
                                </div>

                            </div>
                        </li>
                        <li class="dropdown dropdown-animated scale-left">
                            <div class="pointer" data-toggle="dropdown">
                                <div class="avatar avatar-image  m-h-10 m-r-15">
                                    <img src="~/assets/images/avatars/bongthoi.jpg" alt="">
                                </div>
                            </div>
                            <div class="p-b-15 p-t-20 dropdown-menu pop-profile">
                                <div class="p-h-20 p-b-15 m-b-10 border-bottom">
                                    <div class="d-flex m-r-50">
                                        <div class="avatar avatar-lg avatar-image">
                                            <img src="~/assets/images/avatars/bongthoi.jpg" alt="">
                                        </div>
                                        <div class="m-l-10">
                                            <p style="color:blue" class="m-b-0  font-weight-semibold">@Context.Session.GetString("fullname")</p>
                                          <p>PhamChien96nd</p>
                                        </div>
                                    </div>
                                </div>
                                
                              
                                <a  asp-action="Logout" asp-controller="Accounts" class="dropdown-item d-block p-h-15 p-v-10">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div>
                                            <i class="anticon opacity-04 font-size-16 anticon-logout"></i>
                                            <span class="m-l-10">Đăng xuất</span>
                                        </div>
                                   
                                    </div>
                                </a>
                            </div>
                        </li>
                        <li>
                            <a href="javascript:void(0);" data-toggle="modal" data-target="#quick-view">
                                <i class="anticon anticon-appstore"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- Header END -->
            <!-- Side Nav START -->
            <div class="side-nav">
                <div class="side-nav-inner">
                    <ul class="side-nav-menu scrollable">
                        <li class="nav-item dropdown">
                            <a class="dropdown-toggle" asp-controller="Home" asp-action="Index">
                                <span class="icon-holder">
                                    <i class="anticon anticon-dashboard"></i>
                                </span>
                                <span class="title">Trang chủ</span>

                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="dropdown-toggle" asp-controller="Home" asp-action="LoadData">
                                <span class="icon-holder">
                                    <i class="anticon anticon-dashboard"></i>
                                </span>
                                <span class="title">Cập nhật Xu</span>

                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- Side Nav END -->
            <!-- Page Container START -->
            <div class="page-container">

                <!-- Content Wrapper START -->
                <div class="main-content">
                    @*<div class="page-header">
                            <h2 class="header-title">Orders List</h2>
                            <div class="header-sub-title">
                                <nav class="breadcrumb breadcrumb-dash">
                                    <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
                                    <a class="breadcrumb-item" href="#">Apps</a>
                                    <a class="breadcrumb-item" href="#">E-commerce</a>
                                    <span class="breadcrumb-item active">Orders List</span>
                                </nav>
                            </div>
                        </div>*@
                    <div class="card">
                        <div class="card-body">
                           
                            @RenderBody()
                        </div>
                    </div>
                </div>
                <!-- Content Wrapper END -->
                <!-- Footer START -->
                <footer class="footer">
                    <div class="footer-content">
                        <p class="m-b-0">Phamchien96nd</p>
                        <span>
                            <a href="" class="text-gray m-r-15">Phamchien96nd</a>
                            <a href="" class="text-gray">Phamchien96nd</a>
                        </span>
                    </div>
                </footer>
                <!-- Footer END -->

            </div>
            <!-- Page Container END -->
            <!-- Search Start-->
            <!-- Search End-->
            <!-- Quick View START -->
            <!-- Quick View END -->
        </div>
    </div>


    <!-- Core Vendors JS -->
    <script src="~/assets/js/vendors.min.js"></script>

    <!-- page js -->
    <script src="~/assets/vendors/datatables/jquery.dataTables.min.js"></script>
    <script src="~/assets/vendors/datatables/dataTables.bootstrap.min.js"></script>
    <script src="~/assets/js/pages/e-commerce-order-list.js"></script>

    <!-- Core JS -->
    <script src="~/assets/js/app.min.js"></script>
    @await Component.InvokeAsync("Notyf")
    @RenderSection("Scripts", required: false)
</body>

</html>

Traodoisub/TraoiDoiSubb/Views/Shared/_Login.cshtml
<ul class="navbar-nav">

    <li class="nav-item">
        <a class="nav-link" asp-controller="Accounts" asp-action="Login">Login</a>
    </li>
</ul>